version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "ThermoclineLeviathan"
    groups:
      python-deps:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    reviewers:
      - "ThermoclineLeviathan"
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
